export { MyButton } from './MyButton/MyButton.tsx'
export { Header } from './Header/Header.tsx'
export { CatalogButton } from './CatalogButton/CatalogButton.tsx'
export { Input } from './Input/Input.tsx'
export { RegistrationForm } from './RegistrationForm/RegistrationForm.tsx'
